name: EventStarter
favicon: null
layout_spectrum: 0.520217859884724
typography_spectrum: 0.6717500456143171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.80749556212686
  lightness: 0.5455697134602815
  saturation: 0.29317149030976
  rhythmicContrast: 0.19480221532285213
purpose: []
